#!/usr/bin/env texlua
-- build.lua for babel-malagasy
-- Minimal l3build configuration: this package is a single .sty
-- generated from babel-malagasy.dtx via babel-malagasy.ins.

module = "babel-malagasy"
bundle = ""

ctanpkg   = "babel-malagasy"
pkgname   = "babel-malagasy"

-- Files that make up the source of the package.
sourcefiles = {"babel-malagasy.dtx", "babel-malagasy.ins"}

-- The .sty is generated by docstrip (via the .ins file) into the
-- working directory before tests run; see the "unpack" step below,
-- which l3build drives automatically from installfiles/sourcefiles.
installfiles = {"babel-malagasy.sty"}

-- Documentation source.
typesetfiles = {"babel-malagasy.dtx"}

-- l3build test files (testfiles/*.lvt), checked against the
-- pdfTeX engine actually available in this environment. Other
-- engines (xetex, luatex) are commented out because they were
-- not exercised in this session -- see docs/linguistic-policy.md.
checkengines = {"pdftex"}
stdengine    = "pdftex"

checkdeps    = {}
checkopts    = "-interaction=nonstopmode"

-- babel-malagasy.sty itself is required by every test, so it
-- must be visible from the test working directory; l3build's
-- default "unpack" target (running the .ins file) takes care of
-- generating it there from the .dtx/.ins pair above.

max_print_line = 9999
